#!/bin/bash

if [[ $(/usr/bin/service mysql status) != *start/running* ]]
	then
echo "stopping services"
/usr/sbin/service apache2 stop
/usr/sbin/service nginx stop
/usr/sbin/service mysql stop

echo "sleeping 5 seconds"
#sleep 5

echo "killing garbage"
kill -9 $(ps axf | grep 'mysql' | awk '{print $1}')
kill -9 $(ps axf | grep 'nginx' | awk '{print $1}')
kill -9 $(ps axf | grep 'php-cgi' | awk '{print $1}')

echo "starting services"
/usr/sbin/service apache2 start
/usr/sbin/service nginx start
/usr/sbin/service mysql start

fi
