#!/usr/bin/php
<?php
$homepath='/home/';
$apachelogpath='/var/log/apache2/';

$homelist=`ls -lah $homepath |grep _ |awk '{print \$NF }'`;
$homelist=explode("\n",trim($homelist));

$apachelist=`ls -lah $apachelogpath |grep _ |grep .log |grep -v access.log |grep -v error.log |awk '{print \$NF }'`;
$apachelist=explode("\n",trim($apachelist));

$rem=0;
$rem_m='';
foreach($apachelist as $ak => $av){
	foreach($homelist as $hk => $hv){
		if(strpos($av,$hv)!==FALSE){
			continue 2;
		}
	}
	unlink($apachelogpath.$av);
	$msg="{$av} was be removed.\n";
	$rem_m.=$msg;
	echo $msg;
	$rem++;
}
$msg="+++ A total of {$rem} files were deleted.\n";
$rem_m.=$msg;
echo $msg;
file_put_contents('remove_broken_logs.log',$rem_m);
